- 다양한 방법으로 ndarray 생성

In [1]:
import numpy as np

# ndarray 만들기, np.array()
n-dimensional 배열(array)

In [3]:
np.array(10)  # scalar

array(10)

In [6]:
# 1차원 ndarray 만들기 , vector

In [7]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [8]:
print(arr)

[1 2 3 4 5]


In [9]:
print([1, 2, 3, 4, 5])

[1, 2, 3, 4, 5]


In [10]:
type(arr)

numpy.ndarray

# shape, size, ndim, len(), dtype

In [11]:
arr

array([1, 2, 3, 4, 5])

#### .shape

In [12]:
arr.shape

# (5, )  tuple 형태의 결과, 
# ndarray 가 몇차원데이터인지, 몇개의 데이터로 구성되었는지 보여줌

(5,)

#### .size

In [15]:
arr.size   # 데이터의 개수,  shape 와는 다른 의미

5

#### .ndim

In [17]:
arr.ndim   # 몇차원?

1

In [19]:
len(arr.shape)  # arr.ndim 과 언제가 같은 값.

1

#### len()

In [20]:
len(arr)   # .size 와는 다르다

5

#### .dtype

In [21]:
arr.dtype  # ndarray 의 자료형

dtype('int32')

In [22]:
a = [10, 'hello', 20, 3.13]  

# list 는 각 원소의 데이터 타입이 달라도 되나
# naarray 는 데이터 타입이 하나로 관리 된다.

In [23]:
np.array([10, 3.14, 20, 4.2])

array([10.  ,  3.14, 20.  ,  4.2 ])

In [24]:
# numpy 자료형
# arr1이나 arr2는 int64라는 자료형을 갖는 것에 반해 arr3는 float64라는 자료형을 갖는다.
# 이는 arr3내부 데이터를 살펴보면 3.5라는 실수형 데이터를 갖기 때문임을 알 수 있다.
# numpy에서 사용되는 자료형은 아래와 같다. (자료형 뒤에 붙는 숫자는 몇 비트 크기인지를 의미한다.)

# 부호가 있는 정수 int(8, 16, 32, 64)
# 부호가 없는 정수 uint(8 ,16, 32, 54)
# 실수 float(16, 32, 64, 128)
# 복소수 complex(64, 128, 256)
# 불리언 bool
# 문자열 string_
# 파이썬 오프젝트 object
# 유니코드 unicode_

In [25]:
np.int32

numpy.int32

In [26]:
np.float64

numpy.float64

In [27]:
arr2 = np.array(['a', '3.14', '2', '0', '12'])
arr2.dtype

# dtype('<U4')  4글자 유니코드 문자열

dtype('<U4')

## 2차원 ndarray 생성

In [28]:
x = np.array([[2, 3, 4], [1, 2, 4]]) 
x

array([[2, 3, 4],
       [1, 2, 4]])

In [29]:
[[2, 3, 4], [1, 2, 4]]

[[2, 3, 4], [1, 2, 4]]

In [30]:
[[2, 3, 4], [1, 2]]

[[2, 3, 4], [1, 2]]

In [31]:
np.array([[2, 3, 4], [1, 2]]) 

<ipython-input-31-784f83a6bddb>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[2, 3, 4], [1, 2]])


array([list([2, 3, 4]), list([1, 2])], dtype=object)

#### ndim, size, shape, dtype, len()

In [33]:
x

array([[2, 3, 4],
       [1, 2, 4]])

In [34]:
x.shape

(2, 3)

In [35]:
x.ndim

2

In [36]:
len(x.shape)

2

In [37]:
x.size

6

In [38]:
len(x)

2

In [39]:
x.dtype

dtype('int32')

In [42]:
arr

array([1, 2, 3, 4, 5])

In [43]:
x

array([[2, 3, 4],
       [1, 2, 4]])

In [44]:
arr[2]

3

In [45]:
x[0][2]

4

In [46]:
x[1]  # 2차원 array 의 원소는 1차원 array

array([1, 2, 4])

## 3차원 ndarray 만들기
2차원 array ?  = (1차원 )array 를 갖고 있는 array <br>
3차원 array ?  = 2차원 array 를 갖고 있는 array <br>
4차원 array ?  = 1차원 array 를 갖고 있는 array 

In [47]:
"""
array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[101, 102, 103, 104],
        [201, 202, 203, 204],
        [301, 302, 303, 304]]])
"""
None

In [48]:
z = np.array([
    [
        [1, 2, 3, 4], 
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ], 
    [
        [101, 102, 103, 104], 
        [201, 202, 203, 204], 
        [301, 302, 303, 304], 
    ]
])

z

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[101, 102, 103, 104],
        [201, 202, 203, 204],
        [301, 302, 303, 304]]])

In [49]:
z.shape  # 2 x 3 x 4

(2, 3, 4)

In [50]:
z.ndim

3

In [51]:
z.size

24

In [52]:
len(z)

2

In [53]:
z.dtype

dtype('int32')

#### 똑같은 값이라도 차원이 다를수 있다

In [54]:
np.array(10)

array(10)

In [55]:
np.array([10])

array([10])

In [56]:
np.array([[10]])

array([[10]])

In [57]:
np.array([[[10]]])

array([[[10]]])

### np.arange() 함수로 생성하기
파이썬의 range() 거의 동일

In [58]:
# np.array(iterable)
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [62]:
# 도전) 5 ~ 100 사이의 5의 배수로 구성된 ndarray 
"""
array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])
"""
None

In [63]:
np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [64]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [65]:
np.arange(3, 10, dtype=np.float64)

array([3., 4., 5., 6., 7., 8., 9.])

In [66]:
np.arange((3, 10))

TypeError: arange: scalar arguments expected instead of a tuple.

## np.arange() + reshape()

#### reshape 함수 활용
 - ndarray의 형태, 차원을 바꾸기 위해 사용
 - 머신러닝, 데이터 프로세싱에서 매주 자주 사용됨. (차원변환)

In [68]:
np.arange(12).reshape(2, 6)  # 2 x 6, 2차원 array 로 reshape

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [69]:
np.arange(12).reshape(2, 5)  # 개수 (size) 맞지 않으면 에러

ValueError: cannot reshape array of size 12 into shape (2,5)

In [70]:
np.arange(12).reshape(3, 2, 2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

## np.ones(), np.zeros() 로 생성하기

In [71]:
np.ones(5)  # size 5, 1차원 array

array([1., 1., 1., 1., 1.])

In [72]:
np.ones(5, dtype=np.int32)

array([1, 1, 1, 1, 1])

In [73]:
np.ones(5, dtype="int")

array([1, 1, 1, 1, 1])

In [74]:
np.ones((2, 3))  # 2 x 3, 2차원 array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [87]:
np.ones(6).reshape(2, 3)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [75]:
np.ones((2, 3, 4)) # ( 2 x 3 x 4 ) 3차원 array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [76]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## np.empty(), np.full() 로 생성하기

In [78]:
np.empty((3, 4))

# 초기화가 안된 값들로 만든 array (쓰레기값 들어감)

# 초기화가 안되있어서 빠르게 생성된다.
# 물론 0 으로 되어 있는 경우도 있지만, 항상 보장되는 건 아니다 (주의!)

array([[1.13591395e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.89146896e-307, 2.36033586e+184, 2.19223741e-076,
        5.53632441e+174],
       [8.32379765e-071, 2.92992297e-057, 9.95517451e-043,
        4.46879299e-062]])

In [79]:
np.full((3, 4), 7)    # 7 로만 이루어진 3 x 4 array

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### np.eye로 생성하기
 - 단위 행렬 생성  
 - 2차원, 행과 열의 크기가 같다
 - 대각선 값이 1 이로 나머지는 0
 - 선형대수 등 행렬곱에서 중요한 행렬




In [80]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.linspace() 로 생성

In [83]:
np.linspace(1, 10, 3)

# (start, stop, num)
# 1 부터 10 까지의 전체의 수 중에서 균일한 간격이 되도록 3개가 되도록 나눈 array 생성 (3등분)

array([ 1. ,  5.5, 10. ])

In [84]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])