# random 사용하여 array  생성하기
 - random 서브모듈 함수를 통해 ndarray 생성하기
 - 무작위 데이터 생성
 - 머신러닝에선, weight 값을 '무작위'로 설정한뒤 train 하면서 model 에 맞게 fit 해나가게 된다.

In [1]:
import numpy as np

## np.random

In [2]:
# rand: 0부터 1사이의 균일 분포 [0, 1)  uniform distribution
# randn: 가우시안 표준 정규 분포
# randint: 균일 분포의 정수 난수

#### rand 함수
 - 0, 1사이 [0, 1) 의 분포로 랜덤한 ndarray 생성

In [ ]:
# np.random.   # tab 눌러보면 무수히 많은 난수 발생 관련 함수들 확인 가능!

In [22]:
np.random.rand(10)

array([0.50325874, 0.36887471, 0.70855812, 0.39929871, 0.40914667,
       0.02239866, 0.25725701, 0.87842177, 0.92512909, 0.21802871])

In [24]:
np.random.rand(2, 3)  # 2 x 3 2차원 랜덤 array

array([[0.58330795, 0.82854132, 0.19689031],
       [0.3661144 , 0.25741366, 0.04211437]])

In [26]:
np.random.rand(4, 5, 3)  # 4 x 5 x 3  3차원 랜덤 array (tensor 텐서)

array([[[0.40375806, 0.50873869, 0.91451951],
        [0.71940689, 0.12922731, 0.74070098],
        [0.49676315, 0.18934115, 0.2995481 ],
        [0.8811944 , 0.6919159 , 0.76132897],
        [0.04802117, 0.05749477, 0.9166991 ]],

       [[0.22908336, 0.34287841, 0.58385946],
        [0.51840105, 0.17070961, 0.28828707],
        [0.92138487, 0.82865171, 0.53122889],
        [0.20282263, 0.79633917, 0.13754717],
        [0.62604204, 0.67017914, 0.24162236]],

       [[0.50742417, 0.20774597, 0.18291636],
        [0.36036847, 0.32929133, 0.45404261],
        [0.68984128, 0.28578972, 0.28334493],
        [0.17981017, 0.6459405 , 0.99796147],
        [0.07036392, 0.19341145, 0.80065015]],

       [[0.06081714, 0.65806145, 0.3712522 ],
        [0.91306759, 0.33143299, 0.5515087 ],
        [0.2238781 , 0.83556659, 0.6154036 ],
        [0.40075026, 0.82868794, 0.86785681],
        [0.21951415, 0.26669849, 0.51604808]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성
 - 단순히 [0, 1) 사이의 값이 아닌 정규분포 (음수값도 갖게 된다)
 
 - rand() 는 uniform 한 분포에서 값을 가져오고
 - randn() 은 normal distribution 에서 값을 가져온다
 
 ![normal](https://www.itl.nist.gov/div898/handbook/pmc/section5/gifs/normal.gif)

In [56]:
np.random.randn(5)

array([-0.91576688, -0.86403325,  0.31637507,  0.55943968, -0.38263064])

In [57]:
np.random.randn(3, 4)  # 3 x 4   정규분포에서 샘플링(sampling) 한 값.

array([[-0.73633124,  1.75836713, -0.97705877, -0.1382338 ],
       [-1.12666764,  0.45871804, -1.00582781,  1.96042116],
       [-0.3245095 , -0.02646746, -0.77883629, -0.0521283 ]])

In [58]:
np.random.randn(3, 4, 2, 2)

array([[[[ 0.17663684,  0.32916117],
         [-0.19274469, -0.30439679]],

        [[-0.95205323, -1.50398904],
         [ 1.41588961, -0.64770288]],

        [[-1.00417381, -1.13549516],
         [ 0.554013  ,  0.28546522]],

        [[-0.55147615, -0.04146009],
         [-0.39479712, -1.0466529 ]]],


       [[[ 0.15348796,  0.62351278],
         [ 1.56563157,  1.22821366]],

        [[-0.46961094, -0.31397595],
         [-0.38426283,  0.97921407]],

        [[-0.01753671,  0.76090387],
         [-1.81649781, -0.52491764]],

        [[ 0.68879393, -1.17132956],
         [-0.65813355, -0.35333268]]],


       [[[ 0.00570736, -0.83766227],
         [-1.0437342 ,  1.32235619]],

        [[ 0.46275795,  0.20098701],
         [-0.81355114,  0.4342228 ]],

        [[-1.47739054,  0.57910098],
         [-0.66362827,  0.38780711]],

        [[-0.90260052, -1.58587431],
         [-1.45274868, -1.5806916 ]]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [59]:
np.random.randint(5)   # 0 ~ 4 사이의 정수  [0, 5)

3

In [133]:
np.random.randint(1, 10)  # 1 ~ 9 사이의 정수  [1, 10)

9

In [141]:
# size 값
np.random.randint(1, 100, (3, 5))  # (low, high=None, size=None)

array([[ 1, 44, 66, 50, 72],
       [73, 50,  3, 42, 17],
       [66, 13, 95, 74, 25]])

In [142]:
np.random.randint(1, 100, (3, 5, 2))

array([[[11, 46],
        [43, 14],
        [59, 94],
        [73, 52],
        [99, 16]],

       [[ 5, 57],
        [77, 22],
        [86, 11],
        [44, 55],
        [70, 51]],

       [[46, 85],
        [35, 73],
        [55, 97],
        [48, 29],
        [24, 90]]])

In [ ]:
# 위 3가지 함수가 np.random 에서 가장 많이 사용되는 함수!

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용
 
 - 데이터 실험, 인공지능 학습 하다가, 무언가 직전에 생성된 값으로 다시 실행해야 할때가 있다.  (그런데 랜덤값이 계속 바뀌면 곤란)

In [150]:
# seed() 를 사용하지 않는 경우
np.random.randn(3, 4)    # <-- 랜덤값이 계속 바뀐다.

array([[-0.68630297,  1.41407796,  0.36230345,  1.6248821 ],
       [-0.4805024 ,  1.76395017,  0.03196672, -0.69451211],
       [-1.41149784,  0.51180352, -0.96414268,  0.16934275]])

In [161]:
# np.random.seed(정수)
np.random.seed(100)
np.random.randn(3, 4) # <-- seed() 함수 호출한 '직후' 에 random 의 함수를 호출하면 값이 고정됨.

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

In [168]:
np.random.randn(3, 4) # 그러나, 그 다음은 seed() 의 영향을 받지 않는다

array([[ 0.7788224 ,  0.42823287,  0.10887199,  0.02828363],
       [-0.57882582, -1.1994512 , -1.70595201,  0.36916396],
       [ 1.87657343, -0.37690335,  1.83193608,  0.00301743]])

In [169]:
np.random.seed(20)   # seed 값이 바뀌면 아래 random 값도 바뀌게 된다.
np.random.randn(3, 4) 

array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088]])

#### choice()
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링 (뽑기!)
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [188]:
np.random.choice(100)  # 첫번째 parameter 가 정수인경우.  0 ~ 99

43

In [223]:
np.random.choice([10, 20, 30])  # 첫번째 parameter 가 1-D array-like

30

In [224]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [240]:
np.random.choice(np.arange(1, 10, 2))

1

In [242]:
np.random.choice(100, (3, 4))  # size 명시 가능

array([[56, 56, 58, 79],
       [27, 50, 74, 69],
       [ 2, 57, 23, 95]])

In [243]:
np.random.choice(10, (3, 4))  # 중복 허용

array([[5, 5, 9, 6],
       [9, 9, 5, 2],
       [9, 6, 1, 8]])

In [256]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])   # 이 경우 type 은 실수가 된다.
np.random.choice(x, size=(2, 2))   # 중복 허용됨.

array([[2.6, 1.5],
       [2.6, 3. ]])

In [253]:
# replace=False  : 중복 허용 안함
np.random.choice(x, size=(2, 2), replace=False)  

array([[2.6, 1.5],
       [1. , 3. ]])

In [257]:
np.random.choice(x, size=(3, 3), replace=False)    # 따라서 이건 에러

ValueError: Cannot take a larger sample than population when 'replace=False'

In [258]:
# 확률 분포에 대한 이해가 깊고, 활용하실수 있다면 
# 해당 확률 분포의 이름으로 제공되는 함수들을 사용하여 샘플링 하면 된다.

### np.random.shuffle() 섞기

In [259]:
bb = np.arange(10)
bb

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [262]:
np.random.shuffle(bb)  # 주의! 원본이 변화된다!

# 함수 수행결과 None ... -->  원본 변화 시키는 함수일 가능성 99.9999.. %

In [261]:
bb

array([8, 5, 4, 1, 6, 9, 3, 0, 7, 2])

In [263]:
np.sort(bb)
# 함수 수행결과 있다  --> 원본 변화 시키지 않는 함수

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [264]:
bb

array([7, 4, 1, 8, 6, 5, 3, 9, 2, 0])

In [265]:
np.sort(bb)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### unique, bincount
고유원소, 개수 구하기

In [266]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [267]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
a

array(['a', 'b', 'b', 'c', 'a'], dtype='<U1')

In [270]:
# return_counts=True  등장빈도를 담은 array 도 리턴
index, count = np.unique(a, return_counts=True)

In [271]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [272]:
count

array([2, 2, 1], dtype=int64)