# index, slice
- 개념적으로는 파이썬의 인덱싱, 슬라이싱과 거의 동일

In [1]:
import numpy as np

#### 인덱싱
 - 파이썬 리스트와 동일한 개념으로 사용
 - ,를 사용하여 각 차원의 인덱스에 접근 가능
 - 인덱싱 할때마다 차원감소

### 1차원 벡터 인덱싱

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x[0]  # 첫번째 원소

0

In [5]:
x[9], x[-1]  # 마지막 원소

(9, 9)

In [7]:
# 네번째 원소는
x[3]

3

In [8]:
# 특정 인덱스의 '값' 변경
x[3] = 100
x

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [9]:
x[10]  # IndexError

IndexError: index 10 is out of bounds for axis 0 with size 10

### 2차원 행렬(matrix) 인덱싱

In [12]:
x = np.arange(10).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
x.shape, x.ndim, x.dtype, x.size, len(x)

((2, 5), 2, dtype('int32'), 10, 2)

In [18]:
x[0]

# 0번째 원소 --> 1차원 array 
# index 을 한다는 것은 -> 한차원 감소한 데이터 원소 추출

array([0, 1, 2, 3, 4])

In [19]:
x[1][0]

5

In [21]:
# numpy 에선 아래 두가지 방식의 index 사용 가능!!
x[0][2], x[0, 2]  # <-- 콤마로 가능! (list 에선 불가능했다!)

# numpy 에선 후자와 같은 방법 사용을 추천합니다.

(2, 2)

In [22]:
# 7 
x[1, 2]

7

In [23]:
# 9
x[1, -1]

9

## 3차원 텐서 인덱싱

In [24]:
x = np.arange(36).reshape(3, 4, 3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [25]:
x[0] # 결과는 2차원

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
x[1, 2]

array([18, 19, 20])

In [27]:
x[1, 2, 1]

19

## 슬라이싱
 - 리스트, 문자열 slicing과 동일한 개념으로 사용
 - ,를 사용하여 각 차원 별로 슬라이싱 가능
 - 슬라이싱은 차원 변화 없다

### 1차원 벡터 슬라이싱

In [28]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [30]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# step 가능
x[::2]

array([0, 2, 4, 6, 8])

In [33]:
x[1::3]  #????

array([1, 4, 7])

In [34]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
# indexing 을 하면 차원이 줄지만,
# slicing 은 해도 차원이 줄지 않는다.  (단순히 자른것이기 때문에)

### 2차원 행렬 슬라이싱

In [37]:
# 리스트의 경우는 어떠했는가?
y = [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]]
y

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]

In [38]:
y[0]

[0, 1, 2, 3, 4]

In [40]:
y[0:1]

[[0, 1, 2, 3, 4]]

In [41]:
y[0:1][1:3]

[]

In [ ]:
# 위 2차원 배열에서
# [[1, 2, 3],
#  [6, 7, 8]]
# 만 가져오기??

# 리스트는 불가능!

In [36]:
x = np.arange(10).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
x[:, :]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
x[:, 1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [44]:
# 위 2차원 배열에서
# [[0, 1],
#  [5, 6]]
# 만 가져오기

In [45]:
x[:, :2]

array([[0, 1],
       [5, 6]])

In [47]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
x[0, :2]  # 앞에는 indexing  이고 뒤는 slicing (차원이 줄었다! 확인!)

array([0, 1])

In [48]:
x[:1, :2]  # 앞에도 slicing.  차원 변화 없다  (위와의 차이 꼭 이해! 중요★)

array([[0, 1]])

### 다차원 array(텐서) ,에서의 slicing

In [49]:
arr2 = np.array([
            [1, 2, 3, 4],
            [ 5,  6,  7,  8],
            [ 9, 10, 11, 12],
            [13, 14, 15, 16]
])

In [50]:
""" 아래와 같이  slicing 하려면?
array([[ 6,  7],
       [10, 11]])
"""
None

In [51]:
arr2[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [52]:
# 주의!
arr2[1:3][1:3]   # arr2[1:3] 의 결과에 [1:3]을 한거다, 차례대로 생각해보면 안다

array([[ 9, 10, 11, 12]])

In [53]:
x = np.arange(54).reshape(2, 9, 3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]]])

In [54]:
# 다음을 slicing 해보자
# [[[0, 1, 2],
#  [3, 4, 5]]]   <-- 3차원 유지!

In [57]:
x[:1, :2, :]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [58]:
x[0, :2, :]  # <-- 차원축소

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
x[0][:2][:]  #  numpy 에선 이런 스타일 잘 사용하지 않는다고 했죠?

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 앞으로 데이터분석이나, 인공지능에서 다루게 될 
# 수많은 데이터 들이 적게는 3, 4차원에서 많게는 수십 수백차원 데이터도 다룰수 있다.
# 사실상 3차원 이상의 데이터는 시각화가 거의 불가능 합니다.
# 머리속으로 차근차근 생각하면서 차원 다루기에 익숙해져야 합니다.