# ndarray shape(차원) 변경하기

**차원변환**은 데이터분석 과 인공지능에서 매우 빈번하게 발생되는 작업이니만큼 자유자재로 변환할수 있어야 하고, 머리속으로 내가 변환하는 데이터의 구조가 그려지도록 익숙해져야 합니다

사용 예) 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용 됨

In [1]:
import numpy as np 

## ravel(), np.ravel()
  - [ˈrævl]
  - 다차원배열을 1차원으로 변경 (흔히 **'펼친다'**라고 말함)
  - 'order' 파라미터
    - 'C' - row 우선 변경
    - 'F - column 우선 변경
  - ravel() 은 np 안에 일반 함수로도 있고, 혹은 ndarray 의 멤버함수로서도 존재

In [2]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
x.ravel()  # array의  메소드 ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
np.ravel(x)  # np.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
# order 파라미터 
#   기본값은 '행' 을 기준으로 펼쳐진다   ( order='C')

In [6]:
np.ravel(x, order='C') # row(행) 으로 펼쳐짐 (그런데 약어가 C 이다.. 이런 C...)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
np.ravel(x, order='F') # column(열) 기준으로 펼쳐진다

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [ ]:
# C : C style
# F : Fortran style  

## flatten()
 - 다차원 배열을 1차원으로 변경 
 - ravel과의 차이점: 
     - copy를 생성하여 변경함(즉 원본 데이터가 아닌 복사본을 반환)
     - ndarray 의 멤버함수로만 제공됨
 - 'order' 파라미터
   - 'C' - row 우선 변경
   - 'F - column 우선 변경

In [8]:
y = np.arange(15).reshape(3, 5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# ravel() 과 flatten() 별 차이 없어 보이는데? 

#### ravel() vs. flatten() 차이점

In [10]:
temp = x.ravel()
temp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
temp[0] = 100  # temp 의 값을 변경하면?
temp

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [13]:
x  # temp 값을 바꾸니 x 값도 바뀌었다!!?!?!?

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [14]:
# ravel() 은 내부 데이터 참조를 유지한다. (복사본을 만들지 않는다.)
#  그 결과 ravel 결과는 원본의 데이터 원소를 변경 가능한것이다.

# 복사본을 만들지 않으니까.  성능이 좋다!

# 반면 flatten() 은 복사본을 생성하여 리턴한다

In [15]:
temp2 = y.flatten()  # 복사본을 생성하는 flatten()
temp2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
temp2[0] = 100
temp2  # 복사본이 바뀐거다!

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [18]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
# flatten 도 order 파라미터 있다.

In [20]:
y.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
y.flatten(order='F')

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [22]:
z = np.arange(30).reshape(2, 3, 5)
z

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [23]:
z.ravel()

# 인덱스로 따지면  (뒤의 인덱스 순으로)
# (0, 0, 0) (0, 0, 1) (0, 0, 2)  ...  (1, 2, 3), (1, 2, 4) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
z.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
z

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [26]:
z.shape

(2, 3, 5)

In [27]:
# 생각해보자, 3차원인데? 열기준으로 펼친다???
z.ravel(order='F')

# order='F'
# 인덱스로 따지면 (앞의 인덱스 순으로 증가)  (머리 아프다)
#(0, 0, 0), (1, 0, 0), (0, 1, 0) (1, 1, 0) (0, 2, 0)...

array([ 0, 15,  5, 20, 10, 25,  1, 16,  6, 21, 11, 26,  2, 17,  7, 22, 12,
       27,  3, 18,  8, 23, 13, 28,  4, 19,  9, 24, 14, 29])

## reshape 함수
 - array의 shape을 다른 차원으로 변경
 - 주의할점은 reshape한 후의 결과의 전체 원소 개수와 이전 개수가 같아야 가능
 - 사용 예) 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용 됨

In [2]:
x2 = np.arange(36)
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [29]:
x2.shape

(36,)

In [30]:
x2.reshape(6, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [31]:
x2.reshape(6, 5)

ValueError: cannot reshape array of size 36 into shape (6,5)

In [32]:
# -1 을 차원값으로 줄수 있다?! 

In [33]:
x2.reshape(6, -1)

# 앞의 차원이 정해지면 나머지는 유추할수 있다. 그게 -1 이다
# 정확한 값을 주지 않아도, 계산 귀찮으면 가능

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [34]:
x2.reshape(-1, 12)  # 3 x 12 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [35]:
x2.reshape(6, -1, -1)

ValueError: can only specify one unknown dimension

In [3]:
y2 = x2.reshape(6, 6)
y2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [37]:
y2.shape

(6, 6)

In [38]:
y2.ndim

2

In [39]:
y2.size == x2.size

True

In [4]:
x2.reshape(3, 3, 4)  # 원본 변화 없다.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [5]:
x2  # 원본 변화 없다

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [40]:
k = x2.reshape(3, 3, 4)
k

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [41]:
k.shape, k.ndim, k.size

((3, 3, 4), 3, 36)

In [43]:
x2.reshape(3, -1, 4)  # 3 x 3 x 4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [44]:
x2.reshape(3, -1, 5)

ValueError: cannot reshape array of size 36 into shape (3,newaxis,5)

In [6]:
x2.shape

(36,)

In [8]:
# 직접 shape 에 값 입력 가능 -> 원본 변화
x2.shape = 3, -1, 4 
x2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

## 차원 확장 / 제거

- 차원 확장/제거 하는 동작도 머신러닝에서 많이 사용된다.
- **reshape()** 로 차원 변환(확장/제거) 자유롭게 가능 

## 차원 확장 : np.expand_dims()
- axis로 지정된 '차원을 추가'한다.


## 차원 자동 제거 : squeeze, np.squeeze()

- 차원 중 사이즈가 1인 것을 찾아 스칼라값으로 바꿔 해당 '차원을 제거'한다.

In [47]:
x3 = np.arange(6)
x3 # 1차원이다!

array([0, 1, 2, 3, 4, 5])

In [49]:
x3.shape, x3.ndim, x3.size

((6,), 1, 6)

In [50]:
x3 = x3.reshape(6, 1)
x3  # 2차원

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [51]:
x3.shape, x3.ndim, x3.size

((6, 1), 2, 6)

In [52]:
x3 = x3.reshape(6, 1, 1)
x3 # 3차원

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [53]:
x3.shape, x3.ndim, x3.size

((6, 1, 1), 3, 6)

In [54]:
x3 = x3.reshape(2, 1, 3)
x3

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [56]:
x3 = x3.reshape((6,))   # 다시 1차원으로 (차원제거, 차원축소)
x3

array([0, 1, 2, 3, 4, 5])

In [57]:
x3 = x3.reshape(1, 6)
x3

array([[0, 1, 2, 3, 4, 5]])

In [58]:
x3.shape

(1, 6)

In [59]:
# squeeze() 는 차원중 사이즈가 1인것을 찾아 해당 차원을 제거한다.
x3.squeeze()

array([0, 1, 2, 3, 4, 5])

In [60]:
x4 = np.arange(4).reshape((2, 1, 2))
x4

array([[[0, 1]],

       [[2, 3]]])

In [61]:
x4.shape

(2, 1, 2)

In [62]:
x4.squeeze()

array([[0, 1],
       [2, 3]])

In [63]:
x4.squeeze().shape

(2, 2)

### np.expand_dims() 

- expand_dims는 axis로 지정된 차원을 추가한다.
- axis 는 차원의 축
    - 2차원은 axis => 0, 1
    - 3차원은 axis => 0, 1, 2
    - ...
    
- axis 는 음수값 지원

In [64]:
x5 = np.arange(3)
x5

array([0, 1, 2])

In [65]:
x5.shape

(3,)

In [68]:
# expand_dims(a, axis)
y5 = np.expand_dims(x5, 0)  # 0번째 axis에 새로운 차원 삽입
y5

array([[0, 1, 2]])

In [67]:
y5.shape

(1, 3)

In [69]:
x6 = np.arange(4).reshape((2, 2))
x6

array([[0, 1],
       [2, 3]])

In [70]:
x6.shape

(2, 2)

In [71]:
# (2, 2) -->  (2, 1, 2)
y6 = np.expand_dims(x6, 1) 
y6

array([[[0, 1]],

       [[2, 3]]])

In [72]:
y6.shape

(2, 1, 2)

In [73]:
y6.squeeze()

array([[0, 1],
       [2, 3]])

In [74]:
x6

array([[0, 1],
       [2, 3]])

In [77]:
x6.shape

(2, 2)

In [75]:
# 마지막에 차원 추가하기, axis = -1
y7 = np.expand_dims(x6, -1)
y7

array([[[0],
        [1]],

       [[2],
        [3]]])

In [76]:
np.expand_dims(x6, 2)

array([[[0],
        [1]],

       [[2],
        [3]]])

### np.newaxis

In [78]:
a = np.array([2, 0, 1, 8])
a

array([2, 0, 1, 8])

In [79]:
a.shape

(4,)

In [83]:
a1 = a[np.newaxis, :]   
a1

# 1차원 벡터를 row vector 로 변환했다 라고 함.

array([[2, 0, 1, 8]])

In [84]:
a1.shape

(1, 4)

In [85]:
a2 = a[:, np.newaxis]
a2

# 1차원 벡터는 column vector 로 변환했다 라고도 함.

array([[2],
       [0],
       [1],
       [8]])

In [86]:
a2.shape

(4, 1)

# transpose, T,  swapaxes
전치행렬 (transpose matrix) , 차원 축 바꾸기

![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbtmNz3%2FbtqDk6Xy5nh%2FD7U80E2R3fnahK00cijoY1%2Fimg.png)

In [9]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
a.shape

(3, 5)

In [11]:
np.transpose(a)   # (3, 5) -> (5, 3) 전치행렬

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [12]:
a.T  # transpose() 와 동일

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [13]:
np.swapaxes(a, 0, 1)  # a 의 0번축(차원) 과 1번축을 바꾼다

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#### 3차원 array 의 축 바꾸기

In [14]:
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
b.T # 2 x 3 x 4  => 4 x 3 x 2

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [16]:
b.T.shape

(4, 3, 2)

In [19]:
# 바꾸고 싶은 축의 위치, 순서를 지정 가능
np.transpose(b, (2, 1, 0))   # 2 x 3 x 4 => 4 x 3 x 2

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [20]:
np.transpose(b, (1, 0, 2))   # 2 x 3 x 4 => 3 x 2 x 4

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [21]:
np.transpose(b, (1, 0, 4))

AxisError: axis 4 is out of bounds for array of dimension 3

In [22]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
np.swapaxes(b, 0, 2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])