# Broadcasting

In [1]:
import numpy as np

#### 브로드캐스팅
  - (기본적으로)Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - **다른 Shape을 갖는 array 간 연산** 의 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [Rule 공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

## Shape 이 같은 경우의 연산

In [2]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
y = np.random.rand(15).reshape(3, 5)
y

array([[0.18607011, 0.77662577, 0.10407676, 0.93525635, 0.73010347],
       [0.23440897, 0.29773948, 0.72645424, 0.40279661, 0.33868973],
       [0.09174283, 0.61598742, 0.52803474, 0.96014116, 0.42324604]])

In [7]:
x + y  # 동일한 shape 끼리 연산

array([[ 0.18607011,  1.77662577,  2.10407676,  3.93525635,  4.73010347],
       [ 5.23440897,  6.29773948,  7.72645424,  8.40279661,  9.33868973],
       [10.09174283, 11.61598742, 12.52803474, 13.96014116, 14.42324604]])

In [6]:
x * y

array([[ 0.        ,  0.77662577,  0.20815352,  2.80576904,  2.92041387],
       [ 1.17204487,  1.7864369 ,  5.08517968,  3.2223729 ,  3.04820753],
       [ 0.91742834,  6.77586158,  6.33641694, 12.48183504,  5.9254445 ]])

### Scalar 값과의 연산
차원값이 1인것과의 연산

In [8]:
x + 2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [9]:
x * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [10]:
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [11]:
x + [2]

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [12]:
x + np.array([2])

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [13]:
x + np.array([[[2]]])

array([[[ 2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16]]])

## Shape 이 다른 경우 연산

In [14]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)

In [15]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
b

array([100, 101, 102])

In [17]:
a.shape, b.shape

((4, 3), (3,))

In [18]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [19]:
c = np.arange(1000, 1004)
c

array([1000, 1001, 1002, 1003])

In [20]:
a.shape, c.shape

((4, 3), (4,))

In [21]:
a + c
# (4, 3) + (4,)  <= 맨 뒷 차원 값이 각각 3, 4 다.  다르다! broadcasting안됨!

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [23]:
b, b.shape

(array([100, 101, 102]), (3,))

In [24]:
d = b.reshape(1, 3)
d

array([[100, 101, 102]])

In [25]:
a.shape

(4, 3)

In [26]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [ ]:
# 3차원과 1차원 연산도 가능하고
# 3차원과 2차원 연산도 가능하다

## 도전

In [27]:
arr21 = np.arange(10, 70, 10).reshape(2, 3)
arr21

array([[10, 20, 30],
       [40, 50, 60]])

In [29]:
arr23 = np.array([1, 2])
arr23

array([1, 2])

In [30]:
arr21.shape, arr23.shape

((2, 3), (2,))

In [31]:
arr21 + arr23

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
""" 원하는 결과
array([[11, 22, 31],
       [42, 51, 62]])
"""
None

In [33]:
arr21.reshape(3, 2)  # 2 x 3 --> 3 x 2  로 변형

array([[10, 20],
       [30, 40],
       [50, 60]])

In [34]:
arr21.reshape(3, 2) + arr23

array([[11, 22],
       [31, 42],
       [51, 62]])

In [35]:
(arr21.reshape(3, 2) + arr23).reshape(2, 3)

array([[11, 22, 31],
       [42, 51, 62]])