# linalg 서브모듈
linear algebra (선형대수) 모듈

> 선형대수는 벡터공간을 다루는 대수학

> 고등학교 (행렬, 벡터)  --> 대학 (선형대수)

In [1]:
import numpy as np

In [2]:
# numpy 에서 제공되는 np.linalg  서브모듈 사용

---
## 단위행렬(unit matrix) , 혹은 항등행렬(identity matrix)
주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각 행렬이다.

반드시 정방형 행렬이다

- **np.identity()** 로 생성

![aaa](https://wikimedia.org/api/rest_v1/media/math/render/svg/aa39d64872faa5c81892d545f1b194f41c841395)
![bbb](https://wikimedia.org/api/rest_v1/media/math/render/svg/c1abba1033f4f9ce1c1150c6c16ed84ea3209d5d)
![ccc](https://wikimedia.org/api/rest_v1/media/math/render/svg/3395d9a280403816886e13cf2b01944aa53f28bb)

In [4]:
np.identity(2, dtype=int)  # 2 x 2 단위행렬

array([[1, 0],
       [0, 1]])

In [5]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 행렬의 곱 (Product of Matrix)
![prod](https://t1.daumcdn.net/cfile/tistory/994C213359C46B1B31)
> ※ 주의 일전에 numpy 의 multiply() 와는 다르다

- 단위행렬과의 행렬곱 결과는 언제나 자기자신
- **@ 연산자**
- **np.matmul()**, **np.dot()** 함수

![내적](https://2.bp.blogspot.com/-QjQBnpezC0M/V_8xk6q0d4I/AAAAAAAACNk/xchaXyHM-qYB_aUQjG1crASyCUP5DFyUACLcB/s1600/%25EC%25A0%259C%25EB%25AA%25A9%2B%25EC%2597%2586%25EB%258A%2594%2B%25EA%25B7%25B8%25EB%25A6%25BC.png)

In [6]:
a = np.arange(1, 9).reshape(4, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
b = np.arange(1, 7).reshape(2, 3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a @ b

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51],
       [39, 54, 69]])

In [9]:
np.dot(a, b)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51],
       [39, 54, 69]])

In [10]:
np.matmul(a, b)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51],
       [39, 54, 69]])

In [11]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
a @ np.identity(2, dtype="int")  # 단위행렬과의 행렬곱은 언제나 자기자신

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
np.identity(4, dtype="int") @ a 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### 대각선 성분의 합 trace()

In [15]:
x = np.arange(9).reshape(3, 3)
y = np.arange(11, 20).reshape(3, 3)
x, y

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]))

In [16]:
np.trace(x)

12

In [17]:
np.trace(y)

45

## 역행렬 (Inverse Matrix)
원래 행렬과 행렬곱을 하면 항등행렬이 나오는 행렬

![](https://t1.daumcdn.net/cfile/tistory/2125A64D5301C44E21)

## np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함 (정방형 행렬만 가능)

In [18]:
x = np.random.randint(1, 10, (3, 3))
x

array([[2, 4, 2],
       [2, 9, 1],
       [7, 4, 8]])

In [20]:
y = np.linalg.inv(x)
y

array([[-6.8,  2.4,  1.4],
       [ 0.9, -0.2, -0.2],
       [ 5.5, -2. , -1. ]])

In [21]:
x @ y

array([[ 1.00000000e+00,  4.44089210e-16,  2.22044605e-16],
       [-2.66453526e-15,  1.00000000e+00,  1.11022302e-16],
       [-7.10542736e-15,  1.77635684e-15,  1.00000000e+00]])

In [22]:
np.dot(x, y)

array([[ 1.00000000e+00,  4.44089210e-16,  2.22044605e-16],
       [-2.66453526e-15,  1.00000000e+00,  1.11022302e-16],
       [-7.10542736e-15,  1.77635684e-15,  1.00000000e+00]])

In [23]:
np.matmul(x, y)

array([[ 1.00000000e+00,  4.44089210e-16,  2.22044605e-16],
       [-2.66453526e-15,  1.00000000e+00,  1.11022302e-16],
       [-7.10542736e-15,  1.77635684e-15,  1.00000000e+00]])

### qr 분해 (QR decomposition)   qr() 함수

qr 분해는 어떤 행렬을 직교행렬과 윗삼각행렬의 곱으로 표현

![](http://www.sharetechnote.com/image/EngMath_Matrix_QRDecomposition_01.png)
![](http://www.sharetechnote.com/image/EngMath_Matrix_QRDecomposition_02.png)

In [24]:
# 3 x 3 행렬
exarr = np.array([
    [2, 2, 0],
    [-2, 1, 1],
    [3, 0, 1]
])
exarr

array([[ 2,  2,  0],
       [-2,  1,  1],
       [ 3,  0,  1]])

In [26]:
q, r = np.linalg.qr(exarr)

In [27]:
q

array([[-0.48507125, -0.80845208, -0.33333333],
       [ 0.48507125, -0.56591646,  0.66666667],
       [-0.72760688,  0.16169042,  0.66666667]])

In [28]:
r

array([[-4.12310563, -0.48507125, -0.24253563],
       [ 0.        , -2.18282063, -0.40422604],
       [ 0.        ,  0.        ,  1.33333333]])

In [29]:
np.dot(q, r)

array([[ 2.00000000e+00,  2.00000000e+00,  6.16790569e-18],
       [-2.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00,  5.55111512e-17,  1.00000000e+00]])

## linalg.det()
determinant (행렬식) 값 구하기

![](https://ssl.pstatic.net/images.se2/smedit/2017/8/22/j6nrowmcz88vxc.jpg)

In [30]:
np.linalg.det(exarr)

11.999999999999995

In [31]:
exarr

array([[ 2,  2,  0],
       [-2,  1,  1],
       [ 3,  0,  1]])

## np.linalg.solve
 - 선형대수를 사용하여 일반적인 방정식도 풀이한다
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이(y)와 홍학(x)의 합 : 25, 호랑이 다리와 홍학 다리의 합은 64, 호랑이와 홍학은 각각 몇마리인가?
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


> 참고로 위 Markdown 에 기술된 수식은 LaTeX (레이텍) 구문 사용

In [32]:
A = np.array([[1, 1],
              [2, 4]])

B = np.array([25, 64])

In [34]:
s = np.linalg.solve(A, B)
s

array([18.,  7.])

In [35]:
x, y = s

In [36]:
x, y

(18.0, 7.0)

## 두개 행렬 동일 여부 비교
**np.allclose()** : 오차범위(tolerence) 내에서 같은지 비교 

In [ ]:
# A @ s = B

In [37]:
A @ s

array([25., 64.])

In [38]:
B

array([25, 64])

In [39]:
np.allclose(A @ s, B)

True

In [40]:
np.allclose(q @ r, exarr)

True

In [41]:
q @ r

array([[ 2.00000000e+00,  2.00000000e+00,  6.16790569e-18],
       [-2.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00,  5.55111512e-17,  1.00000000e+00]])

In [42]:
exarr

array([[ 2,  2,  0],
       [-2,  1,  1],
       [ 3,  0,  1]])