In [1]:
import numpy as np

## savetxt() 텍스트 파일로 저장하기

In [2]:
# numpy.savetxt( filename, X, fmt='%.18e', delimiter=' ', 
# 	newline='n', header='', footer='', comment='#', encoding=None)

# 간단히 사용할때는
# numpy.savetxt({파일이름}, {데이터}, 
#            fmt={데이터 형식}, delimiter={데이터간 구분자})

In [3]:
numbers = np.random.randint(1000, 40000, (10, 4))
numbers

array([[18406, 33569, 21284, 34011],
       [ 4767,  5744, 39973,  8547],
       [16918, 19951, 15127,  4114],
       [ 9481, 11475, 39199,  7074],
       [37974,  5164, 10349,  3474],
       [ 1667, 14632, 29688,  8034],
       [ 1095, 19529, 20241, 33753],
       [11051, 17708, 39632, 26861],
       [ 1925, 35118, 35602, 20753],
       [24352, 11891, 24157, 37042]])

In [5]:
np.savetxt("numbers.txt", numbers, fmt="%d", delimiter=',')

In [6]:
!type numbers.txt

18406,33569,21284,34011
4767,5744,39973,8547
16918,19951,15127,4114
9481,11475,39199,7074
37974,5164,10349,3474
1667,14632,29688,8034
1095,19529,20241,33753
11051,17708,39632,26861
1925,35118,35602,20753
24352,11891,24157,37042


## loadtxt()
txt, csv 등 파일 읽기

In [7]:
# numpy.loadtxt(fname, dtype=<class 'float', comments='#', delimiter=' ', 
# 			conerters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, 
#             encoding='bytes', max_rows=None>

# 간단히 사용할때는
# numpy.loadtxt({파일 이름}, delimiter=",")

# 읽어들일 파일의 데이터 타입과 구분자(delimiter)가 무엇인지 먼저 확인하기

In [9]:
# np.loadtxt('numbers.txt')  # 에러

np.loadtxt('numbers.txt', delimiter=',')  # 기본적으로 실수로 읽어 들인다.

array([[18406., 33569., 21284., 34011.],
       [ 4767.,  5744., 39973.,  8547.],
       [16918., 19951., 15127.,  4114.],
       [ 9481., 11475., 39199.,  7074.],
       [37974.,  5164., 10349.,  3474.],
       [ 1667., 14632., 29688.,  8034.],
       [ 1095., 19529., 20241., 33753.],
       [11051., 17708., 39632., 26861.],
       [ 1925., 35118., 35602., 20753.],
       [24352., 11891., 24157., 37042.]])

In [11]:
np.loadtxt('numbers.txt', delimiter=',', dtype='int')

array([[18406, 33569, 21284, 34011],
       [ 4767,  5744, 39973,  8547],
       [16918, 19951, 15127,  4114],
       [ 9481, 11475, 39199,  7074],
       [37974,  5164, 10349,  3474],
       [ 1667, 14632, 29688,  8034],
       [ 1095, 19529, 20241, 33753],
       [11051, 17708, 39632, 26861],
       [ 1925, 35118, 35602, 20753],
       [24352, 11891, 24157, 37042]])

## np.save(), np.load()
*.npy 형식의 object (pickle) 형태로 저장 (바이너리 데이터)

`pickle` 은 파이썬에서 텍스트외의 데이터를 저장하는 형식

In [12]:
np.save("npy_numbers", numbers)  # npy_numbers.npy 로 저장됨.

In [13]:
np.load("npy_numbers.npy")

array([[18406, 33569, 21284, 34011],
       [ 4767,  5744, 39973,  8547],
       [16918, 19951, 15127,  4114],
       [ 9481, 11475, 39199,  7074],
       [37974,  5164, 10349,  3474],
       [ 1667, 14632, 29688,  8034],
       [ 1095, 19529, 20241, 33753],
       [11051, 17708, 39632, 26861],
       [ 1925, 35118, 35602, 20753],
       [24352, 11891, 24157, 37042]])