# copy() & view()
shallow copy , deep copy

In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
b = a  # 대입연산자

In [4]:
b

array([0, 1, 2, 3, 4, 5])

In [5]:
id(a), id(b)

(2456195191232, 2456195191232)

In [6]:
b.shape = 2, 3
b

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
a  # 그렇다.. a도 바뀌어 있다.

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
b[0, 0]  = 100
b

array([[100,   1,   2],
       [  3,   4,   5]])

In [9]:
a

array([[100,   1,   2],
       [  3,   4,   5]])

## view()  => shallow copy
## slicing => shallow copy
ndarray.view() 새로운 array 객체 생성. <br>
shape 변화는 영향 못줌. 그러나 값은 같은 참조

In [10]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
b = a.view()
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
id(a), id(b)  # 다르다!

(2456199615312, 2456199615152)

In [14]:
b.shape = 2, 3
b

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
a   # shape 는 영향을 못준다

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
b[0, 0] = 100
b

array([[100,   1,   2],
       [  3,   4,   5]])

In [18]:
a  # 그러나 ! 값에는 영향을 준다!

array([[100,   1],
       [  2,   3],
       [  4,   5]])

In [19]:
b = a[:, :]

In [20]:
id(a), id(b)

(2456199615312, 2456199647680)

In [21]:
a

array([[100,   1],
       [  2,   3],
       [  4,   5]])

In [22]:
b

array([[100,   1],
       [  2,   3],
       [  4,   5]])

In [23]:
b[1, 1] = 300
b

array([[100,   1],
       [  2, 300],
       [  4,   5]])

In [24]:
a

array([[100,   1],
       [  2, 300],
       [  4,   5]])

In [25]:
# ndarray.view(dtype=None, type=None)
# dtype에 data type이나 ndarray sub-class를 파라미터로 넣어서 원래의 type을 바꿔줄 수 있고, 
# type 자리에는 python type을 넣어서 returned view를 바꿔줄 수 있습니다. (ndarray 또는 Matrix)

In [26]:
arr = np.array([1, 2, 3, 4], dtype='int16')   # 총 8byte (2byte x 4개)
arr

array([1, 2, 3, 4], dtype=int16)

In [27]:
new = arr.view('int32')  # 총 8byte (4byte x 2개)
new

array([131073, 262147])

In [28]:
new = arr.view('int8')
new

array([1, 0, 2, 0, 3, 0, 4, 0], dtype=int8)

## copy() => Deep copy

In [29]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [30]:
b = a.copy()  # deep copy

In [31]:
id(a), id(b)

(2456199722048, 2456199721888)

In [32]:
b.shape = 2, 3
b

array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [34]:
b[0, 0]  = 100
b

array([[100,   1,   2],
       [  3,   4,   5]])

In [35]:
a  # a 는 안바뀌어 있다!!

array([[0, 1],
       [2, 3],
       [4, 5]])