# PyTorch Basic

In [1]:
import torch
import numpy as np

In [2]:
# 연속된 숫자 만들기
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
# torch 는 numpy 와 매우 비슷
torch.arange(9)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
# .shape 확인 가능
nums = torch.arange(9)
nums.shape

torch.Size([9])

In [5]:
type(nums)

torch.Tensor

In [6]:
# numpy() : Tensor 를 numpy 로 리턴해준다
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [7]:
# reshape() 도 된다
nums.reshape(3, 3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [26]:
# rand() : 랜덤으로 만들기
randoms = torch.rand((3, 3))
randoms

tensor([[0.0385, 0.6321, 0.7528],
        [0.5873, 0.7834, 0.6254],
        [0.5963, 0.2952, 0.5414]])

In [27]:
randoms.dtype

torch.float32

In [28]:
# zeros() :
zeros = torch.zeros((3, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [31]:
arr = np.zeros((3, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
arr.shape, arr.size, len(arr)

((3, 3), 9, 3)

In [35]:
zeros.shape

torch.Size([3, 3])

In [37]:
zeros.size() # numpy 와는 다르다.

torch.Size([3, 3])

In [38]:
# ones()
ones = torch.ones((3, 3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

# Operations

In [39]:
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
nums * 3  # broadcast 가능

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [42]:
nums = nums.reshape((3, 3))
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [43]:
nums + nums

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [44]:
result = torch.add(nums, 10)
result

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [45]:
result.numpy()

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]], dtype=int64)

## view()
- view() 는 reshape() 거의 같다..
- view() 는 사실, 훨씬 오래전부터 있어왔다.   (사실 reshape() 를 더 추천한다.)
- 단, 공식 홈페이지 예제에 View 를 사용하기에 소개함.

In [47]:
range_nums = torch.arange(9).reshape(3, 3)
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [48]:
range_nums.view(1, 9)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [49]:
range_nums.view(1, 9).shape

torch.Size([1, 9])

In [50]:
range_nums.view(9)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
range_nums.view(-1)  # 다시 펼치기!

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Slice , Index
numpy 와 비슷

In [52]:
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [53]:
nums[1]

tensor([3, 4, 5])

In [55]:
nums[1, 1], nums[1][1]

(tensor(4), tensor(4))

In [56]:
nums[1:, 1:]

tensor([[4, 5],
        [7, 8]])

In [57]:
# 여기까지는 numpy 와 별 차이 없었다.
# 이제는 새로운 것을 봅시다.

# Compile
tensor 를 특정 device 에 compile 할수 있다.

In [58]:
arr = np.array([1, 1, 1])
arr

array([1, 1, 1])

In [60]:
arr_torch = torch.from_numpy(arr)
arr_torch

tensor([1, 1, 1], dtype=torch.int32)

In [61]:
# 곧바로 타입 변환도 가능
arr_torch.float()

tensor([1., 1., 1.])

In [62]:
# 딥러닝 이니까 GPU 사용도 중요합니다.

In [63]:
# 내 컴에 GPU 를 detect 하기
torch.cuda.is_available()

False

In [65]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [67]:
# to(device) : 특정 device 에 compile 됨.
arr_torch.to(device)

tensor([1, 1, 1], dtype=torch.int32)

[cuda 참조](http://hiuaa.tistory.com/5)<br>
[비교영상] (https://youtu.be/-P28LKWTzrI)

# AutoGrad
'기울기' 를 주어 학습이 되게 하는것.

In [81]:
x = torch.ones(2, 2, requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [83]:
x.grad  # 학습기울기.  현재는 없다!

In [84]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [85]:
y.grad_fn  # function 확인도 가능

In [86]:
# 여기에다가 수식을 더 추가해주자

In [87]:
z = y * y * 3
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [88]:
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [89]:
out.backward()  # back-propagation 수행하면, x 의 기울기를 구할수 있다.

In [90]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [92]:
x.requires_grad  # x 는 기울기를 구하기로 되어 있었다.

True

In [94]:
(x ** 2).requires_grad

True

In [95]:
# 위에서는 '학습모드(train mode)' 가 가능하지만
# 학습모드가 가능하다가도  '테스트모드' 로도 가능해야 겠죠

# no_grad() 사용

In [96]:
with torch.no_grad():  # 이 안에서 돌리면, 기울기를 구하지 않게 된다.
    print((x ** 2).requires_grad)  

False


In [ ]:
    # no_grad() 이면  기울기를 구하지 않게 됩니다.
    # 따라서 batch, normalization dropout 들이 작동 안함
    # 작동 속도는 train mode 일때보다 test mode 가 더 빠르겠죠.