# 연습 : 영화 평점
파일 : rating.csv

## 1. 파일 읽어 들이기

In [1]:
# rating.csv 파일의 내용을 확인하고
# numpy 의 array 로 읽어 들어와 arr_rating 이라는 변수에 담습니다.
# 읽어온뒤 내용도 확인합니다

# userid, moveid, rating

In [28]:
import numpy as np

In [55]:
arr_rating =np.loadtxt(r'D:\DevRoot\DataSet\rating.csv',delimiter=',',dtype='int')

In [56]:
print(arr_rating)

[[1.000e+00 2.000e+00 3.500e+00]
 [1.000e+00 2.900e+01 3.500e+00]
 [1.000e+00 3.200e+01 3.500e+00]
 ...
 [7.020e+02 1.377e+03 1.500e+00]
 [7.020e+02 1.378e+03 1.500e+00]
 [7.020e+02 1.380e+03 3.500e+00]]


## 2.데이터 탐색하기

In [11]:
# arr_rating 의 
# A) 데이터 개수, 차원 정보등을 확인해봅니다.
# B)  0 ~ 4번째 row만 출력해봅니다
# C)  0번째 칼럼(열)만 출력

In [60]:
arr_rating[0:4,0:4]

array([[ 1. ,  2. ,  3.5],
       [ 1. , 29. ,  3.5],
       [ 1. , 32. ,  3.5],
       [ 1. , 47. ,  3.5]])

In [62]:
arr_rating[:,0]

array([  1.,   1.,   1., ..., 702., 702., 702.])

## 3. 영화의 개수 구하기

In [12]:
# 평점이 매겨진 영화의 개수를 구해보세요

In [79]:
np.size(arr_rating[:,2]>0)

100000

In [86]:
(arr_rating[:,2])

array([3.5, 3.5, 3.5, ..., 1.5, 1.5, 3.5])

## 4. 1번 유저에 대한 모든 평점 정보 구하기

In [14]:
# 1번 유저의 '평점 개수' 와 '평점 평균' 을 구하세요

In [88]:
arr_rating[1:]

array([[1.000e+00, 2.900e+01, 3.500e+00],
       [1.000e+00, 3.200e+01, 3.500e+00],
       [1.000e+00, 4.700e+01, 3.500e+00],
       ...,
       [7.020e+02, 1.377e+03, 1.500e+00],
       [7.020e+02, 1.378e+03, 1.500e+00],
       [7.020e+02, 1.380e+03, 3.500e+00]])

## 5. 각 유저별 정보 구하기

In [16]:
# 각 유저별
# 유저 아이디, 평점회수, 평점 평균
# 아래와 같이 list 로 출력

"""
[[1, 175, 3.742857142857143],
 [2, 61, 4.0],
 [3, 187, 4.122994652406417],
 [4, 28, 3.5714285714285716],
 [5, 66, 4.2727272727272725],
 [6, 24, 3.75],
 ...
 ...
"""
None