# 연습 : 영화 평점
파일 : rating.csv

## 1. 파일 읽어 들이기

In [9]:
# rating.csv 파일의 내용을 확인하고
# numpy 의 array 로 읽어 들어와 arr_rating 이라는 변수에 담습니다.
# 읽어온뒤 내용도 확인합니다

# 1 = userid, 2= movieid, 3= rating

In [15]:
import numpy as np
import sys
import os

In [7]:
sys.path.append("D:\DevRoot\DataSet\rating.csv")
filepath = r'D:\DevRoot\DataSet\rating.csv'

In [37]:
a = np.loadtxt(filepath, delimiter=',')
a

array([[1.000e+00, 2.000e+00, 3.500e+00],
       [1.000e+00, 2.900e+01, 3.500e+00],
       [1.000e+00, 3.200e+01, 3.500e+00],
       ...,
       [7.020e+02, 1.377e+03, 1.500e+00],
       [7.020e+02, 1.378e+03, 1.500e+00],
       [7.020e+02, 1.380e+03, 3.500e+00]])

In [39]:
arr_rating = np.array(a) 
arr_rating

array([[1.000e+00, 2.000e+00, 3.500e+00],
       [1.000e+00, 2.900e+01, 3.500e+00],
       [1.000e+00, 3.200e+01, 3.500e+00],
       ...,
       [7.020e+02, 1.377e+03, 1.500e+00],
       [7.020e+02, 1.378e+03, 1.500e+00],
       [7.020e+02, 1.380e+03, 3.500e+00]])

In [43]:
arr_rating[:, 0]  # userid 값들

array([  1.,   1.,   1., ..., 702., 702., 702.])

In [44]:
arr_rating[:, 1]  # movieid 값들

array([   2.,   29.,   32., ..., 1377., 1378., 1380.])

In [45]:
arr_rating[:, 2]  #  평점

array([3.5, 3.5, 3.5, ..., 1.5, 1.5, 3.5])

## 2.데이터 탐색하기  (EDA)

In [11]:
# arr_rating 의 
# A) 데이터 개수, 차원 정보등을 확인해봅니다.
# B)  0 ~ 4번째 row만 출력해봅니다
# C)  0번째 칼럼(열)만 출력

# D) 3번째 칼럼 (영화평점)의 최소, 최대값을 확인해봅시다.

In [49]:
# A 
len(arr_rating), arr_rating.ndim, arr_rating.size, arr_rating.shape

(100000, 2, 300000, (100000, 3))

In [50]:
# B
arr_rating[0:4,:]

array([[ 1. ,  2. ,  3.5],
       [ 1. , 29. ,  3.5],
       [ 1. , 32. ,  3.5],
       [ 1. , 47. ,  3.5]])

In [56]:
# C
arr_rating[:,0].reshape(100000,1)

array([[  1.],
       [  1.],
       [  1.],
       ...,
       [702.],
       [702.],
       [702.]])

In [58]:
# D
np.min(arr_rating[:,2]), np.max(arr_rating[:,2])

(0.5, 5.0)

## 3. 영화의 개수 구하기

In [12]:
# 평점이 매겨진 영화의 개수를 구해보세요

In [61]:
len(arr_rating[:,2] != None)

100000

## 4. 1번 유저에 대한 모든 평점 정보 구하기

In [14]:
# 1번 유저의 '평점 개수' 와 '평점 평균' 을 구하세요

In [73]:
arr_rating[arr_rating[:, 0] == 1]

array([[1.0000e+00, 2.0000e+00, 3.5000e+00],
       [1.0000e+00, 2.9000e+01, 3.5000e+00],
       [1.0000e+00, 3.2000e+01, 3.5000e+00],
       [1.0000e+00, 4.7000e+01, 3.5000e+00],
       [1.0000e+00, 5.0000e+01, 3.5000e+00],
       [1.0000e+00, 1.1200e+02, 3.5000e+00],
       [1.0000e+00, 1.5100e+02, 4.0000e+00],
       [1.0000e+00, 2.2300e+02, 4.0000e+00],
       [1.0000e+00, 2.5300e+02, 4.0000e+00],
       [1.0000e+00, 2.6000e+02, 4.0000e+00],
       [1.0000e+00, 2.9300e+02, 4.0000e+00],
       [1.0000e+00, 2.9600e+02, 4.0000e+00],
       [1.0000e+00, 3.1800e+02, 4.0000e+00],
       [1.0000e+00, 3.3700e+02, 3.5000e+00],
       [1.0000e+00, 3.6700e+02, 3.5000e+00],
       [1.0000e+00, 5.4100e+02, 4.0000e+00],
       [1.0000e+00, 5.8900e+02, 3.5000e+00],
       [1.0000e+00, 5.9300e+02, 3.5000e+00],
       [1.0000e+00, 6.5300e+02, 3.0000e+00],
       [1.0000e+00, 9.1900e+02, 3.5000e+00],
       [1.0000e+00, 9.2400e+02, 3.5000e+00],
       [1.0000e+00, 1.0090e+03, 3.5000e+00],
       [1.

In [74]:
# 1번 유저의 '평점 개수' 
len(arr_rating[arr_rating[:, 0] == 1])

175

In [87]:
# 또는 아래
a = arr_rating[:,0].reshape(100000,1) == 1
len(a[a==1])

175

In [108]:
# 1번 유저의 '평점 평균'
arr_rating[0:175, 2].sum()

655.0

In [109]:
arr_rating[0:175, 2].mean()

3.742857142857143

## 5. 각 유저별 정보 구하기

In [16]:
# 각 유저별
# 유저 아이디, 평점회수, 평점 평균
# 아래와 같이 list 로 출력

"""
[[1, 175, 3.742857142857143],
 [2, 61, 4.0],
 [3, 187, 4.122994652406417],
 [4, 28, 3.5714285714285716],
 [5, 66, 4.2727272727272725],
 [6, 24, 3.75],
 ...
 ...
"""
None

In [112]:
# 2번유저
a = arr_rating[:,0].reshape(100000,1) == 2
len(a[a==1])
arr_rating[175:175+61, 2].mean()

4.0