# 연습 : 영화 평점
파일 : rating.csv

## 1. 파일 읽어 들이기

In [65]:
# rating.csv 파일의 내용을 확인하고
# numpy 의 array 로 읽어 들어와 arr_rating 이라는 변수에 담습니다.
# 읽어온뒤 내용도 확인합니다

# userid, movieid, rating

In [66]:
import numpy as np

In [67]:
arr_rating = np.loadtxt("E:\DevRoot\DataSet\\rating.csv", delimiter=",")
arr_rating[:10]

array([[  1. ,   2. ,   3.5],
       [  1. ,  29. ,   3.5],
       [  1. ,  32. ,   3.5],
       [  1. ,  47. ,   3.5],
       [  1. ,  50. ,   3.5],
       [  1. , 112. ,   3.5],
       [  1. , 151. ,   4. ],
       [  1. , 223. ,   4. ],
       [  1. , 253. ,   4. ],
       [  1. , 260. ,   4. ]])

## 2.데이터 탐색하기

In [68]:
# arr_rating 의 
# A) 데이터 개수, 차원 정보등을 확인해봅니다.
# B)  0 ~ 4번째 row만 출력해봅니다
# C)  0번째 칼럼(열)만 출력

# D) 3번째 칼럼 (영화평점)의 최소, 최대값을 확인해봅시다.

In [69]:
# A)
arr_rating.size, arr_rating.shape, arr_rating.ndim

(300000, (100000, 3), 2)

In [70]:
# B)
arr_rating[:4]

array([[ 1. ,  2. ,  3.5],
       [ 1. , 29. ,  3.5],
       [ 1. , 32. ,  3.5],
       [ 1. , 47. ,  3.5]])

In [71]:
# C)
arr_rating[:, 0]

array([  1.,   1.,   1., ..., 702., 702., 702.])

In [72]:
# D)
arr_rating[:, 2].min(), arr_rating[:, 2].max()

(0.5, 5.0)

## 3. 영화의 개수 구하기

In [73]:
# 평점이 매겨진 영화의 개수를 구해보세요

In [98]:
arr_rating[:, 1]

array([   2.,   29.,   32., ..., 1377., 1378., 1380.])

## 4. 1번 유저에 대한 모든 평점 정보 구하기

In [75]:
# 1번 유저의 '평점 개수' 와 '평점 평균' 을 구하세요

In [106]:
(arr_rating[:, 0] == 1).sum()

175

In [92]:
(arr_rating[arr_rating[:, 0] == 1][:, 2]).mean()

3.742857142857143

In [137]:
len(arr_rating)

100000

## 5. 각 유저별 정보 구하기

In [16]:
# 각 유저별
# 유저 아이디, 평점회수, 평점 평균
# 아래와 같이 list 로 출력

"""
[[1, 175, 3.742857142857143],
 [2, 61, 4.0],
 [3, 187, 4.122994652406417],
 [4, 28, 3.5714285714285716],
 [5, 66, 4.2727272727272725],
 [6, 24, 3.75],
 ...
 ...
"""
None

In [114]:
mlist = []
o = [1, (arr_rating[:, 0] == 1).sum(), (arr_rating[arr_rating[:, 0] == 1][:, 2]).mean()]
mlist.append(o)

mlist

[[1, 175, 3.742857142857143]]

In [138]:
mlist = []
n = 1
for i in len(arr_rating):
    o = [n, (arr_rating[:, 0] == n).sum(), (arr_rating[arr_rating[:, 0] == n][:, 2]).mean()]
    mlist.append(o)
    n += 1

mlist

TypeError: 'int' object is not iterable

In [136]:
mlist = []
n = 1
for i in arr_rating:
    o = [n, (arr_rating[:, 0] == n).sum(), (arr_rating[arr_rating[:, 0] == n][:, 2]).mean()]
    mlist.append(o)
    n += 1

mlist

<ipython-input-136-0d1a4c13a2c4>:4: RuntimeWarning: Mean of empty slice.
  o = [n, (arr_rating[:, 0] == n).sum(), (arr_rating[arr_rating[:, 0] == n][:, 2]).mean()]


[[1, 175, 3.742857142857143],
 [2, 61, 4.0],
 [3, 187, 4.122994652406417],
 [4, 28, 3.5714285714285716],
 [5, 66, 4.2727272727272725],
 [6, 24, 3.75],
 [7, 276, 3.289855072463768],
 [8, 70, 3.8],
 [9, 35, 3.057142857142857],
 [10, 38, 3.8947368421052633],
 [11, 504, 3.945436507936508],
 [12, 36, 3.5277777777777777],
 [13, 62, 3.725806451612903],
 [14, 243, 3.751028806584362],
 [15, 49, 3.204081632653061],
 [16, 60, 3.5166666666666666],
 [17, 26, 4.038461538461538],
 [18, 121, 3.6115702479338845],
 [19, 50, 3.84],
 [20, 28, 3.4285714285714284],
 [21, 163, 3.705521472392638],
 [22, 133, 3.593984962406015],
 [23, 102, 3.9411764705882355],
 [24, 506, 3.3320158102766797],
 [25, 121, 3.6198347107438016],
 [26, 61, 3.4918032786885247],
 [27, 69, 3.847826086956522],
 [28, 32, 2.8125],
 [29, 177, 3.4915254237288136],
 [30, 31, 2.8870967741935485],
 [31, 246, 3.3760162601626016],
 [32, 73, 3.452054794520548],
 [33, 50, 3.3],
 [34, 93, 3.860215053763441],
 [35, 195, 4.248717948717949],
 [36, 20, 