# 연습 : 영화 평점
파일 : rating.csv

## 1. 파일 읽어 들이기

In [2]:
# rating.csv 파일의 내용을 확인하고
# numpy 의 array 로 읽어 들어와 arr_rating 이라는 변수에 담습니다.
# 읽어온뒤 내용도 확인합니다

#userid,movieid,rating

In [3]:
import numpy as np
arr_rating = np.loadtxt('C:\DevRoot\Dropbox\App18\dataset\\rating.txt', delimiter=',', dtype=int)

## 2.데이터 탐색하기

In [4]:
# arr_rating 의 
# A) 데이터 개수, 차원 정보등을 확인해봅니다.
# B)  0 ~ 4번째 row만 출력해봅니다
# C)  0번째 칼럼(열)만 출력

In [5]:
arr_rating.size, arr_rating.shape, len(arr_rating)

(300000, (100000, 3), 100000)

In [6]:
arr_rating[:5]

array([[ 1,  2,  3],
       [ 1, 29,  3],
       [ 1, 32,  3],
       [ 1, 47,  3],
       [ 1, 50,  3]])

In [7]:
arr_rating[:,0]

array([  1,   1,   1, ..., 702, 702, 702])

## 3. 영화의 개수 구하기

In [8]:
# 평점이 매겨진 영화의 개수를 구해보세요

In [9]:
len(set(arr_rating[:,1]))

8227

In [10]:
len(set(arr_rating[:,0]))

702

## 4. 1번 유저에 대한 모든 평점 정보 구하기

In [11]:
# 1번 유저의 '평점 개수' 와 '평점 평균' 을 구하세요

In [12]:
np.sum(arr_rating[:,0]==1)

175

In [13]:
np.mean(arr_rating[:175,2])

3.525714285714286

## 5. 각 유저별 정보 구하기

In [14]:
# 각 유저별
# 유저 아이디, 평점회수, 평점 평균
# 아래와 같이 list 로 출력

"""
[[1, 175, 3.742857142857143],
 [2, 61, 4.0],
 [3, 187, 4.122994652406417],
 [4, 28, 3.5714285714285716],
 [5, 66, 4.2727272727272725],
 [6, 24, 3.75],
 ...
 ...
"""
None

In [15]:
result = np.zeros(shape=(len(set(arr_rating[:,0])),3))
for i in range(len(set(arr_rating[:,0]))):
    result[i][0] = i
    result[i][1] = np.sum(arr_rating[:,0]==i)
    result[i][2] = np.mean(arr_rating[:sum(arr_rating[:,0]==i),2])

result

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


array([[  0.        ,   0.        ,          nan],
       [  1.        , 175.        ,   3.52571429],
       [  2.        ,  61.        ,   3.47540984],
       ...,
       [699.        , 300.        ,   3.76666667],
       [700.        , 157.        ,   3.50318471],
       [701.        ,  24.        ,   3.41666667]])

In [1]:
len(set(arr_rating[:,0]))

NameError: name 'arr_rating' is not defined