# 연습 : 영화 평점
파일 : rating.csv

## 1. 파일 읽어 들이기

In [1]:
# rating.csv 파일의 내용을 확인하고
# numpy 의 array 로 읽어 들어와 arr_rating 이라는 변수에 담습니다.
# 읽어온뒤 내용도 확인합니다

# userid, movieid, rating

In [2]:
import numpy as np

In [27]:
arr_rating = np.loadtxt(r'C:\DevRoot\DataSet\rating.csv', delimiter=',', dtype='float')

## 2.데이터 탐색하기

In [28]:
# arr_rating 의 
# A) 데이터 개수, 차원 정보등을 확인해봅니다.
# B)  0 ~ 4번째 row만 출력해봅니다
# C)  0번째 칼럼(열)만 출력

In [29]:
print('',len(arr_rating),'\n', arr_rating.shape,'\n', arr_rating[0:5],'\n', arr_rating[:,0])

 100000 
 (100000, 3) 
 [[ 1.   2.   3.5]
 [ 1.  29.   3.5]
 [ 1.  32.   3.5]
 [ 1.  47.   3.5]
 [ 1.  50.   3.5]] 
 [  1.   1.   1. ... 702. 702. 702.]


## 3. 영화의 개수 구하기

In [30]:
# 평점이 매겨진 영화의 개수를 구해보세요`

In [32]:
len(arr_rating[arr_rating[:,2] != 0])

100000

In [57]:
len(np.unique(arr_rating[:,1].astype('int')))

8227

## 4. 1번 유저에 대한 모든 평점 정보 구하기

In [14]:
# 1번 유저의 '평점 개수' 와 '평점 평균' 을 구하세요

In [56]:
len(arr_rating[arr_rating[:, 0] == 1]), arr_rating[arr_rating[:, 0] == 1][:, 2].mean(), \
np.mean(arr_rating[arr_rating[:, 0] == 1], axis=0)[2]

(175, 3.742857142857143, 3.742857142857143)

## 5. 각 유저별 정보 구하기

In [16]:
# 각 유저별
# 유저 아이디, 평점회수, 평점 평균
# 아래와 같이 list 로 출력

"""
[[1, 175, 3.742857142857143],
 [2, 61, 4.0],
 [3, 187, 4.122994652406417],
 [4, 28, 3.5714285714285716],
 [5, 66, 4.2727272727272725],
 [6, 24, 3.75],
 ...
 ...
"""
None

In [55]:
[
    [
        i, 
        len(arr_rating[arr_rating[:, 0] == i]), 
        arr_rating[arr_rating[:, 0] == i][:, 2].mean()
    ]
    for i in np.unique(arr_rating[:, 0]).astype('int')
]
    

[[1, 175, 3.742857142857143],
 [2, 61, 4.0],
 [3, 187, 4.122994652406417],
 [4, 28, 3.5714285714285716],
 [5, 66, 4.2727272727272725],
 [6, 24, 3.75],
 [7, 276, 3.289855072463768],
 [8, 70, 3.8],
 [9, 35, 3.057142857142857],
 [10, 38, 3.8947368421052633],
 [11, 504, 3.945436507936508],
 [12, 36, 3.5277777777777777],
 [13, 62, 3.725806451612903],
 [14, 243, 3.751028806584362],
 [15, 49, 3.204081632653061],
 [16, 60, 3.5166666666666666],
 [17, 26, 4.038461538461538],
 [18, 121, 3.6115702479338845],
 [19, 50, 3.84],
 [20, 28, 3.4285714285714284],
 [21, 163, 3.705521472392638],
 [22, 133, 3.593984962406015],
 [23, 102, 3.9411764705882355],
 [24, 506, 3.3320158102766797],
 [25, 121, 3.6198347107438016],
 [26, 61, 3.4918032786885247],
 [27, 69, 3.847826086956522],
 [28, 32, 2.8125],
 [29, 177, 3.4915254237288136],
 [30, 31, 2.8870967741935485],
 [31, 246, 3.3760162601626016],
 [32, 73, 3.452054794520548],
 [33, 50, 3.3],
 [34, 93, 3.860215053763441],
 [35, 195, 4.248717948717949],
 [36, 20, 