# 연습 : 영화 평점
파일 : rating.csv

## 1. 파일 읽어 들이기

In [9]:
# rating.csv 파일의 내용을 확인하고
# numpy 의 array 로 읽어 들어와 arr_rating 이라는 변수에 담습니다.
# 읽어온뒤 내용도 확인합니다

# userid, movieid, rating

In [25]:
import numpy as np
data = np.loadtxt(r'C:\DevRoot\DataSet\rating.csv', delimiter=',', dtype='int')
print(data)

[[   1    2    3]
 [   1   29    3]
 [   1   32    3]
 ...
 [ 702 1377    1]
 [ 702 1378    1]
 [ 702 1380    3]]


In [26]:
id(data)

2033696372976

## 2.데이터 탐색하기

In [11]:
# arr_rating 의 
# A) 데이터 개수, 차원 정보등을 확인해봅니다.
# B)  0 ~ 4번째 row만 출력해봅니다
# C)  0번째 칼럼(열)만 출력

In [28]:
np.sum(data)

893868343

In [27]:
data[0:4]

array([[ 1,  2,  3],
       [ 1, 29,  3],
       [ 1, 32,  3],
       [ 1, 47,  3]])

## 3. 영화의 개수 구하기

In [12]:
# 평점이 매겨진 영화의 개수를 구해보세요

In [30]:
np.sum(data, axis=0)

array([ 36283040, 857246580,    338723])

## 4. 1번 유저에 대한 모든 평점 정보 구하기

In [14]:
# 1번 유저의 '평점 개수' 와 '평점 평균' 을 구하세요

In [34]:
np.mean(data[2])

12.0

## 5. 각 유저별 정보 구하기

In [16]:
# 각 유저별
# 유저 아이디, 평점회수, 평점 평균
# 아래와 같이 list 로 출력

"""
[[1, 175, 3.742857142857143],
 [2, 61, 4.0],
 [3, 187, 4.122994652406417],
 [4, 28, 3.5714285714285716],
 [5, 66, 4.2727272727272725],
 [6, 24, 3.75],
 ...
 ...
"""
None