# 연습 : 영화 평점
파일 : rating.csv

In [1]:
import numpy as np

## 1. 파일 읽어 들이기

In [9]:
# rating.csv 파일의 내용을 확인하고
# numpy 의 array 로 읽어 들어와 arr_rating 이라는 변수에 담습니다.
# 읽어온뒤 내용도 확인합니다

# userid, movieid, rating

In [38]:
arr_rating = np.loadtxt('C:\DveRoot\DataSet\\rating.csv', delimiter=',')
arr_rating

array([[1.000e+00, 2.000e+00, 3.500e+00],
       [1.000e+00, 2.900e+01, 3.500e+00],
       [1.000e+00, 3.200e+01, 3.500e+00],
       ...,
       [7.020e+02, 1.377e+03, 1.500e+00],
       [7.020e+02, 1.378e+03, 1.500e+00],
       [7.020e+02, 1.380e+03, 3.500e+00]])

## 2.데이터 탐색하기 (EDA)

In [11]:
# arr_rating 의 
# A) 데이터 개수, 차원 정보등을 확인해봅니다.
# B)  0 ~ 4번째 row만 출력해봅니다
# C)  0번째 칼럼(열)만 출력

# D) 3번째 칼럼(영화평점)의 최소, 최댓값을 확인해봅시다.

In [20]:
# A) 데이터 개수
len(arr_rating), np.size(arr_rating)

(100000, 300000)

In [22]:
arr_rating.ndim

2

In [12]:
arr_rating.shape

(100000, 3)

In [14]:
# B)  0 ~ 4번째 row만 출력해봅니다
arr_rating[:5,:]

array([[ 1. ,  2. ,  3.5],
       [ 1. , 29. ,  3.5],
       [ 1. , 32. ,  3.5],
       [ 1. , 47. ,  3.5],
       [ 1. , 50. ,  3.5]])

In [16]:
# C) 0번째 칼럼(열)만 출력
arr_rating[:,0]

array([  1.,   1.,   1., ..., 702., 702., 702.])

In [19]:
# D) 3번째 칼럼의 최대, 최솟값
np.max(arr_rating[:,2]), np.min(arr_rating[:,2])

(5.0, 0.5)

In [17]:
arr_rating[:,2]

array([3.5, 3.5, 3.5, ..., 1.5, 1.5, 3.5])

## 3. 영화의 개수 구하기

In [12]:
# 평점이 매겨진 영화의 개수를 구해보세요

In [25]:
arr_rating[:,1]

array([   2.,   29.,   32., ..., 1377., 1378., 1380.])

In [30]:
arr_rating_movie = arr_rating[:,1].astype(np.int32)

In [31]:
np.unique(arr_rating_movie)

array([     1,      2,      3, ..., 125916, 128488, 128594])

In [32]:
len(np.unique(arr_rating_movie))

8227

## 4. 1번 유저에 대한 모든 평점 정보 구하기

In [14]:
# 1번 유저의 '평점 개수' 와 '평점 평균' 을 구하세요

In [44]:
arr_rating[:,0]

array([  1.,   1.,   1., ..., 702., 702., 702.])

In [45]:
np.where(arr_rating[:,0] == 1, arr_rating[:,0], 0)

array([1., 1., 1., ..., 0., 0., 0.])

In [48]:
np.sum(np.where(arr_rating[:,0] == 1, arr_rating[:,0], 0))

175.0

In [49]:
np.sum(np.where(arr_rating[:,0] == 1, arr_rating[:,2], 0))

655.0

In [51]:
np.sum(np.where(arr_rating[:,0] == 1, arr_rating[:,2], 0)) / np.sum(np.where(arr_rating[:,0] == 1, arr_rating[:,0], 0))

3.742857142857143

## 5. 각 유저별 정보 구하기

In [16]:
# 각 유저별
# 유저 아이디, 평점회수, 평점 평균
# 아래와 같이 list 로 출력

"""
[[1, 175, 3.742857142857143],
 [2, 61, 4.0],
 [3, 187, 4.122994652406417],
 [4, 28, 3.5714285714285716],
 [5, 66, 4.2727272727272725],
 [6, 24, 3.75],
 ...
 ...
"""
None